################################# Default configuration ###################
# provide your domain here
baseURL = "pusatbantuan-kcjakpus.netlify.app"
# theme
theme = ["dot-hugo-documentation-theme"]
# site title
title = "Pusat Bantuan"
# disable language
disableLanguages = ["Id"]
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)
# unsafe html
[markup.goldmark.renderer]
unsafe = true


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#02007e"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "lato" # Choose font family from : https://fonts.google.com/

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io

############################## social links ##############################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/BPJSKesehatanRI/?ref=bookmarks"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/BPJSKesehatanRI"
  
[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCuk_RKUxK8Z36lwr1gzDmdQ"
  
[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://instagram.com/bpjskesehatan_ri/"

################################ Bahasa Language ######################
[Languages.id]
languageName = "Id"
languageCode = "id-id"
weight = 1
copyright = "Copyright © 2021 Bidang Kepesertaan & Pelayanan Peserta BPJS Kesehatan Kantor Cabang Jakarta Pusat"

# banner
[Languages.id.params.banner]
title = "Support Center & Knowledge base"
subtitle = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.id.params.cta]
enable = true
title = "Didn't find an answer to your question?"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
# call to action button
[Languages.id.params.cta.button]
enable = true
label = "contact us"
link = "contact"

################## bahasa navigation #################
[[Languages.id.menu.main]]
name = "Beranda"
url = "/"
weight = 1

[[Languages.id.menu.main]]
name = "Faq"
url = "faq"
weight = 2

[[Languages.id.menu.main]]
name = "Kontak"
url = "kontak"
weight = 3

# Dropdown menu
[[Languages.id.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.id.menu.main]]
  parent = "docs"
  name = "Installation"
  url = "installation"
  weight = 1

  [[Languages.id.menu.main]]
  parent = "docs"
  name = "Billing and Pricing"
  url = "billing-pricing"
  weight = 2

  [[Languages.id.menu.main]]
  parent = "docs"
  name = "Features"
  url = "features"
  weight = 3

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 2
copyright = "Copyright © 2021 Bidang Kepesertaan & Pelayanan Peserta BPJS Kesehatan Kantor Cabang Jakarta Pusat"

# banner
[Languages.en.params.banner]
title = "Support Center & Knowledge base"
subtitle = "Find advice and answers from our support team fast or get in touch"
bg_image = "images/banner.jpg"
placeholder = "Have a question? Just ask here or enter terms"

# call to action
[Languages.en.params.cta]
enable = false
title = "Didn't find an answer to your question?"
content = "Musce libero nunc, dignissim quis turpis quis, semper vehicula dolor. Suspendisse tincidunt consequat quam."
# call to action button
[Languages.en.params.cta.button]
enable = false
label = "contact us"
link = "contact"


################## english navigation #################
[[Languages.en.menu.main]]
name = "Home"
url = "/"
weight = 1

# [[Languages.en.menu.main]]
# name = "Faq"
# url = "faq"
# weight = 2

# [[Languages.en.menu.main]]
# name = "contact"
# url = "contact"
# weight = 3

# Dropdown menu
[[Languages.en.menu.main]]
weight = 4
name = "docs"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Daftar Istilah"
  url = "/daftar-istilah"
  weight = 1

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Formulir"
  url = "formulir"
  weight = 2

  [[Languages.en.menu.main]]
  parent = "docs"
  name = "Peraturan dan Regulasi"
  url = "peraturan-dan-regulasi"
  weight = 3

